apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  DEBUG: "False"
  ENVIRONMENT: "production"
  # DATABASE_URL points to the postgres-service inside the cluster
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/college_portal"
